version: '3'

services:
  db:
    image: postgres
  
  assets:
    build:
      dockerfile: docker/development/Dockerfile.gulp
      context: .

    volumes:
      - ./django/assets:/app/project/assets/

    command: npm run watch

  web:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.web
    entrypoint: python3 django/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
      # - cache
      # - assets